In [3]:
    # Import necessary libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, hamming_loss
import numpy as np

    # Load the dataset
    # IMPORTANT: Update this file_path to your exact CSV file location
file_path = 'data_program_recommendation - Copy (tryy1).csv'
    # The 'r' before the string makes it a "raw string", which handles backslashes correctly in Windows paths.
    # Alternatively, you can use forward slashes:
    # file_path = 'C:/Users/Marwina/Desktop/Anacondas/2025-CP_Section_Placement_and_Student_Risk_Prediction/data/MultipleFiles/data_program_recommendation - Copy (tryy1).csv'

df = pd.read_csv(file_path)

    # Display the first few rows of the dataframe to understand its structure
print("Original DataFrame Head:")
print(df.head())
print("\nDataFrame Info:")
df.info()
    

Original DataFrame Head:
  student id  dost_exam_result  filipino grade  English grade  \
0  student 1                 0              89             90   
1  student 2                 0              89             79   
2  student 3                 0              84             90   
3  student 4                 0              87             90   
4  student 5                 0              82             90   

   mathematics grade  science grade  araling panlipunan grade  \
0                 78             86                        87   
1                 89             81                        79   
2                 79             90                        88   
3                 79             87                        79   
4                 82             75                        80   

   Edukasyon sa pagpapakatao grade  \
0                               83   
1                               82   
2                               90   
3                               83   
4  

In [4]:
    # Define input features (X) and output labels (y)

    # Input features are the grades and exam results
    # We exclude 'student id' as it's just an identifier and 'dost_exam_result'
    # if it's considered part of the input criteria rather than a direct grade.
    # Assuming 'dost_exam_result' is an input feature (0 or 1 indicating pass/fail or participation)
    # and not a grade, we'll include it.
    # The grades are from 'filipino grade' to 'Average grade'.
    # 'hetero', 'top 5', 'ste', 'spfl', 'sptve' are our target labels.

X = df[['dost_exam_result', 'filipino grade', 'English grade', 'mathematics grade',
            'science grade', 'araling panlipunan grade', 'Edukasyon sa pagpapakatao grade',
            'Edukasyong panglipunan at pangkabuhayan grade', 'MAPEH grade', 'Average grade']]

    # Output labels are the program eligibility columns
y = df[['hetero', 'top 5', 'ste', 'spfl', 'sptve']]

print("\nInput Features (X) Head:")
print(X.head())
print("\nOutput Labels (y) Head:")
print(y.head())
    


Input Features (X) Head:
   dost_exam_result  filipino grade  English grade  mathematics grade  \
0                 0              89             90                 78   
1                 0              89             79                 89   
2                 0              84             90                 79   
3                 0              87             90                 79   
4                 0              82             90                 82   

   science grade  araling panlipunan grade  Edukasyon sa pagpapakatao grade  \
0             86                        87                               83   
1             81                        79                               82   
2             90                        88                               90   
3             87                        79                               83   
4             75                        80                               84   

   Edukasyong panglipunan at pangkabuhayan grade  MAPEH grad

In [5]:
    # Split the data into training and testing sets (80% train, 20% test)
    # random_state ensures reproducibility of the split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\nTraining set size: {len(X_train)} samples")
print(f"Testing set size: {len(X_test)} samples")
    


Training set size: 544 samples
Testing set size: 136 samples


In [ ]:
    # Initialize a dictionary to store trained models for each label
models = {}
predictions = {}
overall_predictions = []

    # Train a Decision Tree Classifier for each program eligibility label
for label in y.columns:
    print(f"\nTraining model for: {label}")
        # Create a Decision Tree Classifier instance
        # You can tune hyperparameters like max_depth, min_samples_leaf, etc.
        # For now, we'll use default settings.
    model = DecisionTreeClassifier(random_state=42)

        # Train the model on the training data for the current label
    model.fit(X_train, y_train[label])

        # Store the trained model
    models[label] = model

        # Make predictions on the test set for the current label
    y_pred_label = model.predict(X_test)
    predictions[label] = y_pred_label

        # Print accuracy for the current label
    accuracy = accuracy_score(y_test[label], y_pred_label)
    print(f"Accuracy for {label}: {accuracy:.4f}")

    # Combine individual predictions into a single array for overall evaluation
    # This creates a 2D array where each row is a student's predictions across all labels
    overall_predictions = np.array([predictions[label] for label in y.columns]).T

    print("\nSample of combined predictions (first 5 students):")
    print(overall_predictions[:5])
    print("\nSample of actual labels (first 5 students):")
    print(y_test.head())
    


Training model for: hetero
Accuracy for hetero: 1.0000


KeyError: 'top 5'

In [7]:
# Initialize a dictionary to store trained models for each label
models = {}
predictions = {}
overall_predictions = []

# Train a Decision Tree Classifier for each program eligibility label
for label in y.columns:
    print(f"\n--- Processing label: {label} ---") # Debugging print
    try:
        # Create a Decision Tree Classifier instance
        model = DecisionTreeClassifier(random_state=42)

        # Train the model on the training data for the current label
        model.fit(X_train, y_train[label])

        # Store the trained model
        models[label] = model
        print(f"Model for {label} trained and stored.") # Debugging print

        # Make predictions on the test set for the current label
        y_pred_label = model.predict(X_test)
        predictions[label] = y_pred_label
        print(f"Predictions for {label} made and stored.") # Debugging print

        # Print accuracy for the current label
        accuracy = accuracy_score(y_test[label], y_pred_label)
        print(f"Accuracy for {label}: {accuracy:.4f}")

    except Exception as e:
        print(f"An error occurred while processing label '{label}': {e}")
        # This will help us see if any specific label causes a problem during training/prediction
        continue # Skip to the next label if an error occurs for the current one

# After the loop, check what's actually in the 'predictions' dictionary
print("\n--- Contents of 'predictions' dictionary after loop ---")
print(predictions.keys()) # This will show which labels successfully had predictions stored

# Combine individual predictions into a single array for overall evaluation
# This creates a 2D array where each row is a student's predictions across all labels
# Ensure all labels in y.columns are present in predictions.keys()
try:
    overall_predictions = np.array([predictions[label] for label in y.columns]).T
    print("\nOverall predictions successfully combined.")
except KeyError as ke:
    print(f"\nKeyError during overall_predictions combination: {ke}")
    print("This means a label in y.columns was not found in the 'predictions' dictionary.")
    print("Please check the previous error messages for why that label might have failed.")
    # You might want to exit or handle this more gracefully depending on your needs
    # For now, we'll just print the error and stop.
    raise # Re-raise the original KeyError to stop execution if it's critical


print("\nSample of combined predictions (first 5 students):")
print(overall_predictions[:5])
print("\nSample of actual labels (first 5 students):")
print(y_test.head())



--- Processing label: hetero ---
Model for hetero trained and stored.
Predictions for hetero made and stored.
Accuracy for hetero: 1.0000

--- Processing label: top 5 ---
Model for top 5 trained and stored.
Predictions for top 5 made and stored.
Accuracy for top 5: 0.9926

--- Processing label: ste ---
Model for ste trained and stored.
Predictions for ste made and stored.
Accuracy for ste: 1.0000

--- Processing label: spfl ---
Model for spfl trained and stored.
Predictions for spfl made and stored.
Accuracy for spfl: 1.0000

--- Processing label: sptve ---
Model for sptve trained and stored.
Predictions for sptve made and stored.
Accuracy for sptve: 1.0000

--- Contents of 'predictions' dictionary after loop ---
dict_keys(['hetero', 'top 5', 'ste', 'spfl', 'sptve'])

Overall predictions successfully combined.

Sample of combined predictions (first 5 students):
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 0 0 0 0]
 [1 1 0 1 1]
 [1 1 0 0 0]]

Sample of actual labels (first 5 students):
     hetero  t

In [8]:
    # Initialize a dictionary to store trained models for each label
models = {}
predictions = {}
overall_predictions = []

    # Train a Decision Tree Classifier for each program eligibility label
for label in y.columns:
        print(f"\nTraining model for: {label}")
        # Create a Decision Tree Classifier instance
        # You can tune hyperparameters like max_depth, min_samples_leaf, etc.
        # For now, we'll use default settings.
        model = DecisionTreeClassifier(random_state=42)

        # Train the model on the training data for the current label
        model.fit(X_train, y_train[label])

        # Store the trained model
        models[label] = model

        # Make predictions on the test set for the current label
        y_pred_label = model.predict(X_test)
        predictions[label] = y_pred_label

        # Print accuracy for the current label
        accuracy = accuracy_score(y_test[label], y_pred_label)
        print(f"Accuracy for {label}: {accuracy:.4f}")

    # Combine individual predictions into a single array for overall evaluation
    # This creates a 2D array where each row is a student's predictions across all labels
overall_predictions = np.array([predictions[label] for label in y.columns]).T

print("\nSample of combined predictions (first 5 students):")
print(overall_predictions[:5])
print("\nSample of actual labels (first 5 students):")
print(y_test.head())
    


Training model for: hetero
Accuracy for hetero: 1.0000

Training model for: top 5
Accuracy for top 5: 0.9926

Training model for: ste
Accuracy for ste: 1.0000

Training model for: spfl
Accuracy for spfl: 1.0000

Training model for: sptve
Accuracy for sptve: 1.0000

Sample of combined predictions (first 5 students):
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 0 0 0 0]
 [1 1 0 1 1]
 [1 1 0 0 0]]

Sample of actual labels (first 5 students):
     hetero  top 5  ste  spfl  sptve
647       1      1    1     1      1
607       1      1    1     1      1
63        1      0    0     0      0
319       1      1    0     1      1
101       1      1    0     0      0


In [9]:
    # Evaluate the overall multi-label model performance

    # Convert y_test to a NumPy array for consistent comparison
y_test_np = y_test.to_numpy()

    # Hamming Loss: Measures the fraction of labels that are incorrectly predicted.
    # Lower Hamming Loss is better.
h_loss = hamming_loss(y_test_np, overall_predictions)
print(f"\nOverall Hamming Loss: {h_loss:.4f}")

    # Exact Match Ratio (Subset Accuracy): The percentage of samples for which
    # all labels are correctly predicted.
    # Higher Exact Match Ratio is better.
exact_match_ratio = np.all(y_test_np == overall_predictions, axis=1).mean()
print(f"Overall Exact Match Ratio (Subset Accuracy): {exact_match_ratio:.4f}")

    # You can also calculate other multi-label metrics like F1-score, Jaccard similarity, etc.
    # For simplicity, we'll stick to Hamming Loss and Exact Match Ratio for now.
    


Overall Hamming Loss: 0.0015
Overall Exact Match Ratio (Subset Accuracy): 0.9926


In [10]:
    # Example: Make predictions for a new student
    # You need to provide the same input features as used for training
    # The order of features must be the same:
    # ['dost_exam_result', 'filipino grade', 'English grade', 'mathematics grade',
    #  'science grade', 'araling panlipunan grade', 'Edukasyon sa pagpapakatao grade',
    #  'Edukasyong panglipunan at pangkabuhayan grade', 'MAPEH grade', 'Average grade']

    # Example student data:
    # dost_exam_result: 1 (passed)
    # filipino grade: 90
    # English grade: 85
    # mathematics grade: 92
    # science grade: 88
    # araling panlipunan grade: 80
    # Edukasyon sa pagpapakatao grade: 85
    # Edukasyong panglipunan at pangkabuhayan grade: 90
    # MAPEH grade: 82
    # Average grade: 87

new_student_data = pd.DataFrame([[1, 90, 85, 92, 88, 80, 85, 90, 82, 87]],
                                    columns=X.columns)

print("\nNew Student Data:")
print(new_student_data)

recommended_programs = {}
for label, model in models.items():
        # Predict for the new student using each trained model
        prediction = model.predict(new_student_data)[0] # [0] to get the single prediction value
        recommended_programs[label] = "Eligible" if prediction == 1 else "Not Eligible"

print("\nProgram Recommendations for New Student:")
for program, status in recommended_programs.items():
        print(f"- {program.replace('_', ' ').title()}: {status}")
    


New Student Data:
   dost_exam_result  filipino grade  English grade  mathematics grade  \
0                 1              90             85                 92   

   science grade  araling panlipunan grade  Edukasyon sa pagpapakatao grade  \
0             88                        80                               85   

   Edukasyong panglipunan at pangkabuhayan grade  MAPEH grade  Average grade  
0                                             90           82             87  

Program Recommendations for New Student:
- Hetero: Eligible
- Top 5: Eligible
- Ste: Not Eligible
- Spfl: Not Eligible
- Sptve: Not Eligible


In [12]:
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt


In [14]:
# Example: Make predictions for a new student
# (Keep your new_student_data definition as is)

new_student_data = pd.DataFrame([[1, 90, 85, 92, 88, 80, 85, 90, 82, 87]],
                                columns=X.columns)

print("\nNew Student Data:")
print(new_student_data)

recommended_programs = {}
print("\n--- Detailed Program Recommendations and Explanations ---")
for label, model in models.items():
    prediction = model.predict(new_student_data)[0]
    status = "Eligible" if prediction == 1 else "Not Eligible"
    recommended_programs[label] = status

    print(f"\nProgram: {label.replace('_', ' ').title()} - Status: {status}")
    print("Decision Path Explanation:")

    # Get the decision path for the new student
    # This returns the indices of the nodes in the tree that the sample traverses
    node_indicator = model.decision_path(new_student_data)
    leaf_id = model.apply(new_student_data) # Get the leaf node ID

    # Iterate through the nodes in the decision path
    # The decision_path returns a sparse matrix, so we need to convert it to an array
    path_nodes = node_indicator.indices[node_indicator.indptr[0]:node_indicator.indptr[1]]

    # Get feature names for better readability
    feature_names = X.columns.tolist()

    for i, node_id in enumerate(path_nodes):
        # If it's not the leaf node, it's a decision node
        if node_id != leaf_id[0]:
            feature = feature_names[model.tree_.feature[node_id]]
            threshold = model.tree_.threshold[node_id]
            value = new_student_data[feature].iloc[0] # Get the student's value for this feature

            # Determine if the condition was true or false
            if value <= threshold:
                decision = f"({feature} <= {threshold:.2f})"
                branch = "True"
            else:
                decision = f"({feature} > {threshold:.2f})"
                branch = "False"

            print(f"  - Node {i+1}: Student's '{feature}' grade ({value}) led to decision {decision}. Branch: {branch}")
        else:
            # This is the leaf node, which contains the final prediction
            class_value = model.tree_.value[node_id][0][0] # Get the class value (0 or 1)
            # The 'value' in the leaf node represents the counts of samples for each class
            # For a binary classifier, it's usually [count_class_0, count_class_1]
            # We want the class that has the higher count, which is implicitly the prediction.
            # The prediction itself is already stored in 'prediction' variable.
            counts = model.tree_.value[node_id][0]
num_samples = model.tree_.n_node_samples[node_id]

if len(counts) == 1:
    # Only one class present in this leaf
    class_0_count = counts[0]
    class_1_count = 0
else:
    class_0_count = counts[0]
    class_1_count = counts[1]

print(f"  - Final Node (Leaf): This path leads to a prediction of {prediction} for {label}.")
print(f"    (This node contains {num_samples} samples, with {class_0_count} samples of class 0 and {class_1_count} samples of class 1)")



# Print the summary recommendations again
print("\n--- Summary Program Recommendations ---")
for program, status in recommended_programs.items():
    print(f"- {program.replace('_', ' ').title()}: {status}")

# Optional: Visualize one of the trees (e.g., for 'top 5')
# This can be very large for deep trees, so use with caution.
# plt.figure(figsize=(20,10))
# plot_tree(models['top 5'], feature_names=X.columns, class_names=['Not Eligible', 'Eligible'], filled=True, rounded=True)
# plt.title("Decision Tree for 'top 5' Program Eligibility")
# plt.show()



New Student Data:
   dost_exam_result  filipino grade  English grade  mathematics grade  \
0                 1              90             85                 92   

   science grade  araling panlipunan grade  Edukasyon sa pagpapakatao grade  \
0             88                        80                               85   

   Edukasyong panglipunan at pangkabuhayan grade  MAPEH grade  Average grade  
0                                             90           82             87  

--- Detailed Program Recommendations and Explanations ---

Program: Hetero - Status: Eligible
Decision Path Explanation:

Program: Top 5 - Status: Eligible
Decision Path Explanation:
  - Node 1: Student's 'Average grade' grade (87) led to decision (Average grade > 84.50). Branch: False
  - Node 2: Student's 'Edukasyong panglipunan at pangkabuhayan grade' grade (90) led to decision (Edukasyong panglipunan at pangkabuhayan grade > 76.50). Branch: False
  - Node 3: Student's 'filipino grade' grade (90) led to deci

In [15]:
# Example: Make predictions for a new student
# (Keep your new_student_data definition as is)

new_student_data = pd.DataFrame([[0, 78, 75, 82, 80, 80, 75, 79, 78, 79]],
                                columns=X.columns)

print("\nNew Student Data:")
print(new_student_data)

recommended_programs = {}
print("\n--- Detailed Program Recommendations and Explanations ---")
for label, model in models.items():
    prediction = model.predict(new_student_data)[0]
    status = "Eligible" if prediction == 1 else "Not Eligible"
    recommended_programs[label] = status

    print(f"\nProgram: {label.replace('_', ' ').title()} - Status: {status}")
    print("Decision Path Explanation:")

    # Get the decision path for the new student
    # This returns the indices of the nodes in the tree that the sample traverses
    node_indicator = model.decision_path(new_student_data)
    leaf_id = model.apply(new_student_data) # Get the leaf node ID

    # Iterate through the nodes in the decision path
    # The decision_path returns a sparse matrix, so we need to convert it to an array
    path_nodes = node_indicator.indices[node_indicator.indptr[0]:node_indicator.indptr[1]]

    # Get feature names for better readability
    feature_names = X.columns.tolist()

    for i, node_id in enumerate(path_nodes):
        # If it's not the leaf node, it's a decision node
        if node_id != leaf_id[0]:
            feature = feature_names[model.tree_.feature[node_id]]
            threshold = model.tree_.threshold[node_id]
            value = new_student_data[feature].iloc[0] # Get the student's value for this feature

            # Determine if the condition was true or false
            if value <= threshold:
                decision = f"({feature} <= {threshold:.2f})"
                branch = "True"
            else:
                decision = f"({feature} > {threshold:.2f})"
                branch = "False"

            print(f"  - Node {i+1}: Student's '{feature}' grade ({value}) led to decision {decision}. Branch: {branch}")
        else:
            # This is the leaf node, which contains the final prediction
            class_value = model.tree_.value[node_id][0][0] # Get the class value (0 or 1)
            # The 'value' in the leaf node represents the counts of samples for each class
            # For a binary classifier, it's usually [count_class_0, count_class_1]
            # We want the class that has the higher count, which is implicitly the prediction.
            # The prediction itself is already stored in 'prediction' variable.
            counts = model.tree_.value[node_id][0]
num_samples = model.tree_.n_node_samples[node_id]

if len(counts) == 1:
    # Only one class present in this leaf
    class_0_count = counts[0]
    class_1_count = 0
else:
    class_0_count = counts[0]
    class_1_count = counts[1]

print(f"  - Final Node (Leaf): This path leads to a prediction of {prediction} for {label}.")
print(f"    (This node contains {num_samples} samples, with {class_0_count} samples of class 0 and {class_1_count} samples of class 1)")



# Print the summary recommendations again
print("\n--- Summary Program Recommendations ---")
for program, status in recommended_programs.items():
    print(f"- {program.replace('_', ' ').title()}: {status}")

# Optional: Visualize one of the trees (e.g., for 'top 5')
# This can be very large for deep trees, so use with caution.
# plt.figure(figsize=(20,10))
# plot_tree(models['top 5'], feature_names=X.columns, class_names=['Not Eligible', 'Eligible'], filled=True, rounded=True)
# plt.title("Decision Tree for 'top 5' Program Eligibility")
# plt.show()



New Student Data:
   dost_exam_result  filipino grade  English grade  mathematics grade  \
0                 0              78             75                 82   

   science grade  araling panlipunan grade  Edukasyon sa pagpapakatao grade  \
0             80                        80                               75   

   Edukasyong panglipunan at pangkabuhayan grade  MAPEH grade  Average grade  
0                                             79           78             79  

--- Detailed Program Recommendations and Explanations ---

Program: Hetero - Status: Eligible
Decision Path Explanation:

Program: Top 5 - Status: Not Eligible
Decision Path Explanation:
  - Node 1: Student's 'Average grade' grade (79) led to decision (Average grade <= 84.50). Branch: True

Program: Ste - Status: Not Eligible
Decision Path Explanation:
  - Node 1: Student's 'dost_exam_result' grade (0) led to decision (dost_exam_result <= 0.50). Branch: True

Program: Spfl - Status: Not Eligible
Decision Path E

In [16]:
# Example: Make predictions for a new student
# (Keep your new_student_data definition as is)

new_student_data = pd.DataFrame([[0, 90, 95, 92, 90, 90, 89, 94, 93, 93]],
                                columns=X.columns)

print("\nNew Student Data:")
print(new_student_data)

recommended_programs = {}
print("\n--- Detailed Program Recommendations and Explanations ---")
for label, model in models.items():
    prediction = model.predict(new_student_data)[0]
    status = "Eligible" if prediction == 1 else "Not Eligible"
    recommended_programs[label] = status

    print(f"\nProgram: {label.replace('_', ' ').title()} - Status: {status}")
    print("Decision Path Explanation:")

    # Get the decision path for the new student
    # This returns the indices of the nodes in the tree that the sample traverses
    node_indicator = model.decision_path(new_student_data)
    leaf_id = model.apply(new_student_data) # Get the leaf node ID

    # Iterate through the nodes in the decision path
    # The decision_path returns a sparse matrix, so we need to convert it to an array
    path_nodes = node_indicator.indices[node_indicator.indptr[0]:node_indicator.indptr[1]]

    # Get feature names for better readability
    feature_names = X.columns.tolist()

    for i, node_id in enumerate(path_nodes):
        # If it's not the leaf node, it's a decision node
        if node_id != leaf_id[0]:
            feature = feature_names[model.tree_.feature[node_id]]
            threshold = model.tree_.threshold[node_id]
            value = new_student_data[feature].iloc[0] # Get the student's value for this feature

            # Determine if the condition was true or false
            if value <= threshold:
                decision = f"({feature} <= {threshold:.2f})"
                branch = "True"
            else:
                decision = f"({feature} > {threshold:.2f})"
                branch = "False"

            print(f"  - Node {i+1}: Student's '{feature}' grade ({value}) led to decision {decision}. Branch: {branch}")
        else:
            # This is the leaf node, which contains the final prediction
            class_value = model.tree_.value[node_id][0][0] # Get the class value (0 or 1)
            # The 'value' in the leaf node represents the counts of samples for each class
            # For a binary classifier, it's usually [count_class_0, count_class_1]
            # We want the class that has the higher count, which is implicitly the prediction.
            # The prediction itself is already stored in 'prediction' variable.
            counts = model.tree_.value[node_id][0]
num_samples = model.tree_.n_node_samples[node_id]

if len(counts) == 1:
    # Only one class present in this leaf
    class_0_count = counts[0]
    class_1_count = 0
else:
    class_0_count = counts[0]
    class_1_count = counts[1]

print(f"  - Final Node (Leaf): This path leads to a prediction of {prediction} for {label}.")
print(f"    (This node contains {num_samples} samples, with {class_0_count} samples of class 0 and {class_1_count} samples of class 1)")



# Print the summary recommendations again
print("\n--- Summary Program Recommendations ---")
for program, status in recommended_programs.items():
    print(f"- {program.replace('_', ' ').title()}: {status}")

# Optional: Visualize one of the trees (e.g., for 'top 5')
# This can be very large for deep trees, so use with caution.
# plt.figure(figsize=(20,10))
# plot_tree(models['top 5'], feature_names=X.columns, class_names=['Not Eligible', 'Eligible'], filled=True, rounded=True)
# plt.title("Decision Tree for 'top 5' Program Eligibility")
# plt.show()



New Student Data:
   dost_exam_result  filipino grade  English grade  mathematics grade  \
0                 0              90             95                 92   

   science grade  araling panlipunan grade  Edukasyon sa pagpapakatao grade  \
0             90                        90                               89   

   Edukasyong panglipunan at pangkabuhayan grade  MAPEH grade  Average grade  
0                                             94           93             93  

--- Detailed Program Recommendations and Explanations ---

Program: Hetero - Status: Eligible
Decision Path Explanation:

Program: Top 5 - Status: Eligible
Decision Path Explanation:
  - Node 1: Student's 'Average grade' grade (93) led to decision (Average grade > 84.50). Branch: False
  - Node 2: Student's 'Edukasyong panglipunan at pangkabuhayan grade' grade (94) led to decision (Edukasyong panglipunan at pangkabuhayan grade > 76.50). Branch: False
  - Node 3: Student's 'filipino grade' grade (90) led to deci

In [17]:
import pickle

# Assuming your decision tree model is named 'model' (or a dict of models)
# For example, if you have multiple models in a dict called 'models':
with open('decision_tree_models.pkl', 'wb') as f:
    pickle.dump(models, f)

# Or if you have a single model:
# with open('decision_tree_model.pkl', 'wb') as f:
#     pickle.dump(model, f)
